### ISSUE TITLE
Extended mode not working in F#

### ISSUE THREAD

**Issue by latkin** [JoeMayo/LinqToTwitter#125]
I've been successfully using LinqToTwitter in F#, but recently ran into limitations with standard query mode truncating long tweets. I RTFMed, saw this is expected Twitter API behavior and it's solved by opting in to "Extended" mode.

I saw that C# examples accomplish this by adding a clause `&& tweet.TweetMode == TweetMode.Extended`.

My working F# code for standard mode was:

```
query {
    for tweet in context.Status do
    where (tweet.Type = StatusType.Mentions)
    select tweet
}
```

I modified this to:

```
query {
    for tweet in context.Status do
    where (tweet.Type = StatusType.Mentions && tweet.TweetMode = TweetMode.Extended)
    select tweet
}
```

But this resulted in exception:

```
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at System.Int32.Parse(String s)
   at LinqToTwitter.StatusRequestProcessor`1.BuildUrlParameters(Dictionary`2 parameters, String url)
   at LinqToTwitter.StatusRequestProcessor`1.BuildUrl(Dictionary`2 parameters)
   at LinqToTwitter.TwitterContext.<ExecuteAsync>d__127`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LinqToTwitter.TwitterQueryProvider.<ExecuteAsync>d__8`1.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at LinqToTwitter.TwitterQueryable`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at Microsoft.FSharp.Collections.SeqModule.ToArray[T](IEnumerable`1 source)
   at Microsoft.FSharp.Collections.ArrayModule.OfSeq[T](IEnumerable`1 source)
   at Test.Program.main(String[] _arg1) in C:\src\FSharpScratch\FSharpScratch\Program.fs:line 89
```

I debugged it and found culprit here https://github.com/JoeMayo/LinqToTwitter/blob/e099a6cfde7a92c75dab7126f05ef4232931d44c/src/LinqToTwitter/LinqToTwitter.Shared/Status/StatusRequestProcessor.cs#L337-L341

Debugger shows that `parameters` dict in my case contains `"Extended"` string, not `"1"` as expected:

![image](https://user-images.githubusercontent.com/5943573/39830910-a31ea700-5377-11e8-81e9-06622b26935b.png)

I'm not sure if this is a LinqToTwitter bug, or quite possibly it's an F# compiler bug where the `query` expression gets translated into LINQ in some way that's incompatible with how C# is doing it.

Thankfully I found a workaround!

```
query {
    for tweet in context.Status do
    where (tweet.Type = StatusType.Mentions && (int tweet.TweetMode) = 1)
    select tweet
}
```

**Comment by latkin** [comment]
One easy fix on LinqToTwitter side would be to make StatusRequestProcessor more lenient to this case, and optionally accept the enum name as well as the int value:

```
if (parameters.ContainsKey(nameof(TweetMode))) 
{ 
    if(int.TryParse(parameters[nameof(TweetMode)])
    {
        ...
    }
    else
    {
        Enum.Parse<TweetMode>(parameters[nameof(TweetMode)])
        ...
    }
}
```

If you think this is ok I can float a PR for it

**Comment by JoeMayo** [comment]
Sorry, it took a while to respond. This looks like it would make a good PR. I think my unit tests are covering this, but we also might want one that exercises the new branch too.
