### ISSUE TITLE
Could not authenticate you. when i registered webhook  Authorization Required 

### ISSUE THREAD

**Issue by vivekanandrajak** [JoeMayo/LinqToTwitter#147]
at LinqToTwitter.Net.TwitterErrorHandler.<HandleUnauthorizedAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at LinqToTwitter.Net.TwitterErrorHandler.<ThrowIfErrorAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at LinqToTwitter.TwitterExecute.<HandleResponseAsync>d__61.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at LinqToTwitter.TwitterExecute.<PostFormUrlEncodedToTwitterAsync>d__60`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at LinqToTwitter.TwitterContext.<AddAccountActivityWebhookAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Linq2TwitterDemos_Console.AccountActivityDemos.<AddWebhookAsync>d__2.MoveNext() in D:\twiter\LinqToTwitter-master\LinqToTwitter-master\Samples\net46\CSharp\ConsoleSamples\AccountActivityDemos.cs:line 85

**Comment by JoeMayo** [comment]
Closing - this is pretty old and I don't recall ever engaging on it.
