### ISSUE TITLE
Unhandled Error - LINQ to Twitter wasn't able to parse Twitter error message.

### ISSUE THREAD

**Issue by bassemyehia** [JoeMayo/LinqToTwitter#216]
System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred. (Unhandled Error - LINQ to Twitter wasn't able to parse Twitter error message. Please copy this message, with the Detail property contents and the query you were using (how to reproduce) to Joe Mayo at https://github.com/JoeMayo/LinqToTwitter/issues.)
  Source=System.Private.CoreLib
  StackTrace:
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at ConsoleDemos.VisualBasic.Program.Main() in C:\Users\Bassem\Downloads\LinqToTwitter-main\Samples\LinqToTwitter6\Console\ConsoleDemos.VisualBasic\ConsoleDemos.VisualBasic\Program.vb:line 10

  This exception was originally thrown at this call stack:
    [External Code]
    ConsoleDemos.VisualBasic.Program.SendTweet() in Program.vb

Inner Exception 1:
TwitterQueryException: Unhandled Error - LINQ to Twitter wasn't able to parse Twitter error message. Please copy this message, with the Detail property contents and the query you were using (how to reproduce) to Joe Mayo at https://github.com/JoeMayo/LinqToTwitter/issues.

Unhandled exception. System.AggregateException: One or more errors occurred. (Unhandled Error - LINQ to Twitter wasn't able to parse Twitter error message. Please copy this message, with the Detail property contents and the query you were using (how to reproduce) to Joe Mayo at https://github.com/JoeMayo/LinqToTwitter/issues.)
 ---> LinqToTwitter.Common.TwitterQueryException: Unhandled Error - LINQ to Twitter wasn't able to parse Twitter error message. Please copy this message, with the Detail property contents and the query you were using (how to reproduce) to Joe Mayo at https://github.com/JoeMayo/LinqToTwitter/issues.
   at LinqToTwitter.Net.TwitterErrorHandler.BuildAndThrowTwitterQueryException(String responseStr, HttpResponseMessage msg)
   at LinqToTwitter.Net.TwitterErrorHandler.HandleGenericErrorAsync(HttpResponseMessage msg)
   at LinqToTwitter.Net.TwitterErrorHandler.ThrowIfErrorAsync(HttpResponseMessage msg)
   at LinqToTwitter.OAuth.AuthorizerBase.HttpPostAsync(String oauthUrl, IDictionary`2 parameters)
   at LinqToTwitter.OAuth.AuthorizerBase.PostAccessTokenAsync(IDictionary`2 accessTokenParams)
   at LinqToTwitter.OAuth.XAuthAuthorizer.AuthorizeAsync()
   at ConsoleDemos.VisualBasic.Program.SendTweet() in C:\Users\Bassem\Downloads\LinqToTwitter-main\Samples\LinqToTwitter6\Console\ConsoleDemos.VisualBasic\ConsoleDemos.VisualBasic\Program.vb:line 18
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at ConsoleDemos.VisualBasic.Program.Main() in C:\Users\Bassem\Downloads\LinqToTwitter-main\Samples\LinqToTwitter6\Console\ConsoleDemos.VisualBasic\ConsoleDemos.VisualBasic\Program.vb:line 10

C:\Users\Bassem\Downloads\LinqToTwitter-main\Samples\LinqToTwitter6\Console\ConsoleDemos.VisualBasic\ConsoleDemos.VisualBasic\bin\Debug\net5.0\ConsoleDemos.VisualBasic.exe (process 9116) exited with code -532462766.

**Comment by JoeMayo** [comment]
Hi,

Thank you for posting. This line from the stack trace says that you're using the XAuthAuthorizer:

    at LinqToTwitter.OAuth.XAuthAuthorizer.AuthorizeAsync()

The XAuthAuthorizer is for using username/password, like old-style Twitter API (back in the 2008 timeframe). The Twitter API has since changed to use OAuth as their primary means of authorization. Now, to use the XAuthAuthorizer, you need permission from Twitter. Please review the [LINQ to Twitter Security Documentation](https://www.linqtotwitter.com/Securing-Your-Applications.html) for more info on how to use OAuth. 

The stack trace also indicates that you're using VB.NET. Forturnately, I've upgraded the entire [VB.NET Sample Project](https://github.com/JoeMayo/LinqToTwitter/tree/main/Samples/LinqToTwitter6/Console/ConsoleDemos.VisualBasic) with many more examples (and growing). It will have examples of how to use OAuth with VB.

In the meantime, I'll try to reproduce this and see why the error message isn't parsing.

[@JoeMayo](https://twitter.com/JoeMayo)

**Comment by JoeMayo** [comment]
Found the problem - It was an XML formatted message that Twitter was responding with. Here's the message:

    <?xml version='1.0' encoding='UTF-8'?>
        <errors>
            <error code="87">Client is not permitted to perform this action</error>
        </errors>

As I mentioned before, you need Twitter permission to use XAuth.

**Comment by jguadagno** [comment]
With the latest update I started to receive this exception.  The details of the exception are
```json
{"client_id":"<removed number>",
"detail":"When authenticating requests to the Twitter API v2 endpoints, you must use keys and tokens from a Twitter developer App that is attached to a Project. You can create a project via the developer portal.",
"registration_url":"https://developer.twitter.com/en/docs/projects/overview",
"title":"Client Forbidden","required_enrollment":"Standard Basic",
"reason":"client-not-enrolled","type":"https://api.twitter.com/2/problems/client-forbidden"}
```

**Comment by jguadagno** [comment]
@JoeMayo, that was the issue. I thought that you might want to update the exception handling since the messaging says "I don't know how to parse this message, reach out..."
