### ISSUE TITLE
L2T v6.7.1 - Console Demos -> Streaming -> Filter Stream Error

### ISSUE THREAD

**Issue by JeepNL** [JoeMayo/LinqToTwitter#230]
I'm using 

 * LinqToTwitter v6.7.1 
 * .NET 6 RC 1 
 * Visual Studio 2022 Preview 4

Below the error I receive when trying the v6 C# Console Demo Filtered Streaming sample in `StreamDemos.cs`. I've tried it with the default rules ie: memes with media & cats with media and with 2 of my own rules with the hashtags `#blazor` & `#dotnet` without media. I did a test waiting for 25 streamed filtered tweets and it gives the error with every tweet.

One other question: since yesterday I've access to the Early Access v2 Twitter API. I've read that LinqToTwitter v6x supports these new API endpoints as well as the current 1x API.  How do I know which endpoint (v1 or v2) I'm using? Maybe a bit of a stupid question, but it is not clear to me yet 😉

```
Error during streaming: Error parsing twitter message. Please create a new issue on the LINQ to Twitter site at https://github.com/JoeMayo/LinqToTwitter/issues with this info.

Message Type: Unknown, Message Text:
 {"data":{"id":"1439258182371749891","text":"RT @TeamPatriot007: #include&lt;stdio.h&gt;\n#include&lt;conio.h&gt;\nvoid main()\n{\nprintf{\"#AI #MachineLearning #DEEPWEB};\ngetch()\n#forex #bot #Website."},"matching_rules":[{"id":"1439257300594745346","tag":"Add hashtag dotnet"}]}
Exception Details: System.Text.Json.JsonException: The JSON value could not be converted to System.UInt64. Path: $.matching_rules[0].id | LineNumber: 0 | BytePositionInLine: 252.
 ---> System.InvalidOperationException: Cannot get the value of a token type 'String' as a number.
   at System.Text.Json.Utf8JsonReader.TryGetUInt64(UInt64& value)
   at System.Text.Json.Utf8JsonReader.GetUInt64()
   at System.Text.Json.Serialization.Converters.UInt64Converter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at LinqToTwitter.StreamContent.ParseJson(String json)
```

**Comment by mobilitygoinc** [comment]
I have experienced the same problem (JSON convert to System.UInt64), precisely same error as mentioned above.

My environment is different:

- LinqToTwitter v6.7.1
- Visual Studio 2019 (for Mac)
- .NET 5.0.401

**Comment by JoeMayo** [comment]
I see the problem and can reproduce it easily. Thanks for reporting.

**Comment by JoeMayo** [comment]
This is deployed as [LINQ to Twitter v6.8.0](https://github.com/JoeMayo/LinqToTwitter/releases/tag/v6.8.0) and deployed to [NuGet](https://www.nuget.org/packages/linqtotwitter/).

On telling the difference between versions, I have somewhat of a convention. If a new v2 endpoint clearly replaces it's v1.1 counterpart, I remove the v1.1 query and replace it with v2. There are cases, like with Search, where the APIs operate side-by-side, where I call the new v2 query `TwitterSearch`, instead of the v1.1 `Search` they both still work. Additionally, the documentation contains the URL to the Twitter API endpoint for each command or query at the bottom of the page.

That said, I'm open to suggestion if anyone has ideas.

**Comment by JoeMayo** [comment]
This is deployed as [LINQ to Twitter v6.8.0](https://github.com/JoeMayo/LinqToTwitter/releases/tag/v6.8.0) and deployed to [NuGet](https://www.nuget.org/packages/linqtotwitter/).

On telling the difference between versions, I have somewhat of a convention of removing v1.1 endpoints when the v2 endpoint clearly replaces them. In other cases, such as `TwitterSearch` (v2) and `Search` (v1.1), both versions are still running and the `TwitterXxx` convention signals the v2 version. Also, the Documentation has a URL to the Twitter API documentation for each endpoint. Ideas on how to improve are welcome.

**Comment by JeepNL** [comment]
Thanks for the new release! 

And about the v1 & v2 versions: it's completely clear to me now and I think your vision is the best of both worlds. I really don't mind what endpoint I'm using, I just want it to work and will work when they deprecate v1.1.

Furthermore: I think you're ideas about moving forward with LinqToTwitter (v6+), supporting (.net 2.0 standard, as long it's still here) / .NET Core 3/5 / .NET 6+ is also the best option. .NET 6 will be an LTS also, so IMO you can drop support for .NET 3.x when 6 has been released as well, but that's just my opinion. Upgrading after .NET Core 3 is easy, and I think everybody should do it.

**Comment by JeepNL** [comment]
Oh, I think it's save to close this issue as is has been resolved.
