### ISSUE TITLE
v6.8.0 - Stream - cancelTokenSrc.Cancel(); doesn't close (?) the stream.

### ISSUE THREAD

**Issue by JoeMayo** [JoeMayo/LinqToTwitter#237]
### Discussed in https://github.com/JoeMayo/LinqToTwitter/discussions/234

<div type='discussions-op-text'>

<sup>Originally posted by **JeepNL** September 22, 2021</sup>
When I run the C# v6 Stream Console Sample [StreamDemos.cs](https://github.com/JoeMayo/LinqToTwitter/blob/main/Samples/LinqToTwitter6/Console/ConsoleDemo.CSharp/ConsoleDemo.CSharp/StreamDemos.cs) and when the `count` is at its max value (in this example 5) the stream stops but it doesn't close (?) it. 

When I select '**0. Filter Stream**' from the "**Streaming Demos**" menu for the second time after a successful first run I receive the error below. I've read the FAQ, but I couldn't find info about this error. I've also tried it with `strm.CloseStream();` and `strm.Dispose()`.

When I close the app and run it again (from Visual Studio 2022), I can use '**0. Filter Stream**' from the menu again. I've also tried to wait a couple of minutes after stream cancellation, but that hasn't any effect as well.

**Sample code:**
```
await
    (from strm in twitterCtx.Streaming
                            .WithCancellation(cancelTokenSrc.Token)
     where strm.Type == StreamingType.Filter
     select strm)
    .StartAsync(async strm =>
    {
        await HandleStreamResponse(strm);

        if (count++ >= 5)
            cancelTokenSrc.Cancel();
    });

```

**Error:**
```
LinqToTwitter.Common.TwitterQueryException: This stream is currently at the maximum allowed connection limit. - Please visit the LINQ to Twitter FAQ (at the HelpLink) for help on resolving this error.
   at LinqToTwitter.Net.TwitterErrorHandler.HandleTooManyRequestsAsync(HttpResponseMessage msg)
   at LinqToTwitter.Net.TwitterErrorHandler.ThrowIfErrorAsync(HttpResponseMessage msg)
   at LinqToTwitter.Provider.TwitterExecute.QueryTwitterStreamAsync(Request request)
   at LinqToTwitter.TwitterContext.ExecuteAsync[T](Expression expression, Boolean isEnumerable)
   at LinqToTwitter.Provider.TwitterQueryProvider.ExecuteAsync[TResult](Expression expression)
   at LinqToTwitter.TwitterExtensions.ToListAsync[T](IQueryable`1 query)
   at LinqToTwitter.TwitterExtensions.StartAsync(IQueryable`1 streaming, Func`2 callback)
   at L2T.StreamDemos.DoFilterStreamAsync(TwitterContext twitterCtx) in D:\Repos\L2T\L2T\StreamDemos.cs:line 78
   at L2T.StreamDemos.RunAsync(TwitterContext twitterCtx) in D:\Repos\L2T\L2T\StreamDemos.cs:line 22
   at Program.<<Main>$>g__DoDemosAsync|0_0() in D:\Repos\L2T\L2T\Program.cs:line 48
   at Program.<Main>$(String[] args) in D:\Repos\L2T\L2T\Program.cs:line 10
```</div>

**Comment by JeepNL** [comment]
FYI - I noticed something else with streaming, it probably(*) hasn't anything to do with the LinqToTwitter library, but with the Twitter v2 API itself.

With v2 it's (finally) possible to filter streams at API level with (for example) `-is:retweet -is:reply -is:quote` so you don't get automatically all RTs/Quote Tweets and/or Reply's in your stream back to you. 

[StreamDemos.cs](https://github.com/JoeMayo/LinqToTwitter/blob/main/Samples/LinqToTwitter6/Console/ConsoleDemo.CSharp/ConsoleDemo.CSharp/StreamDemos.cs) sample:
When you display the value of `count` in the console you'll see `HandleStreamResponse` is called many times where `tweet == null`. I tried to use `strm?.Content` to see what is inside the stream, but the length is always `0`. First of all I don't know how to use `strm?.Content` so probably I'm using it wrong, or maybe I need to use something completely different, but I wonder what Twitter is streaming so `HandleStreamResponse` is called.

I'd like to know how much bandwidth it's using and those 'null tweets' are added to the 'Monthly Tweet Cap Usage' (see screenshot below). With the rule I'm now using this isn't really important, but If I want to stream/follow an account with (tens of) millions of followers maybe it can be if this has something to do with followers interaction. (I haven't tested it yet with such a popular account).

The rule I'm using: 
`new StreamingAddRule { Tag = "#blazor OR #dotnet", Value = "(#blazor OR #dotnet) lang:en -is:retweet -is:reply -is:quote -is:nullcast" }`
(Rule building: https://developer.twitter.com/en/docs/twitter-api/tweets/filtered-stream/integrate/build-a-rule)

![image](https://user-images.githubusercontent.com/39458532/134767319-d4e1e567-8fcf-4fbf-9956-289a66b4ae00.png)

(*) I've added this comment here, because it's also about streaming and `StreamDemos.cs` and because maybe it has something to do with LinqToTwitter, I just don't know.
