### ISSUE TITLE
OAuth 2.0 - RefreshToken/RevokeToken: Missing valid authorization header

### ISSUE THREAD

**Issue by JeepNL** [JoeMayo/LinqToTwitter#265]
When I try to implement LT2 RefreshToken/RevokeToken in my Blazor WASM LT2 Oauth 2.0 project  I get the same(?) error at the server web API at `lt2Tokens.AccessToken = await auth.RefreshTokenAsync();` as I got earlier with CompleteAsync: `await auth.CompleteAuthorizeAsync(code, state);`

### Missing valid authorization header ###

 * `offline.access` is in the 'Scopes' [List](https://github.com/JeepNL/LINQ_To_Twitter_OAuth2_Sample/blob/b273f07fceedb8fe302258de273c7498d256f56d/LINQ_To_Twitter_OAuth2_Sample/Server/Controllers/OAuth2Controller.cs#L40)
 * I don't know if it's the same error as earlier or if I do something wrong
 * I don't know if I need to use 
   * `CredentialStore = new OAuth2CredentialStore`
   * or `CredentialStore = new OAuth2SessionCredentialStore(HttpContext.Session)`
 * And I don't know if I can/need to use
   * `OAuth2Authorizer auth = new()`
   * or `MvcOAuth2Authorizer auth = new()`

I tried several combinations of `new OAuth2CredentialStore` / `new OAuth2SessionCredentialStore(HttpContext.Session)` & `OAuth2Authorizer auth = new()` / `MvcOAuth2Authorizer auth = new()` but they give all the same result: Missing valid authorization header

To reproduce this error you can download my [repo](https://github.com/JeepNL/LINQ_To_Twitter_OAuth2_Sample) and start it. The repo needs an extra 'twitterkeys.ini' file at the server level/Web API as described in the [README](https://github.com/JeepNL/LINQ_To_Twitter_OAuth2_Sample/blob/master/README.md)

(Web API) -  Server/[OAuth2Controller.cs](https://github.com/JeepNL/LINQ_To_Twitter_OAuth2_Sample/blob/master/LINQ_To_Twitter_OAuth2_Sample/Server/Controllers/OAuth2Controller.cs)

	[HttpPost]
	public async Task<ActionResult<L2TBase>> RefreshToken(L2TBase lt2Tokens)
	{
		Console.WriteLine($"\n\n***** INPUT - lt2Base.AccessToken: {lt2Tokens.AccessToken}");

		OAuth2Authorizer auth = new()
		{
			CredentialStore = new OAuth2CredentialStore
			//CredentialStore = new OAuth2SessionCredentialStore(HttpContext.Session)
			{
				ClientID = _configuration["TwitterClientID"],
				RefreshToken = lt2Tokens.RefreshToken
			}
		};

		lt2Tokens.AccessToken = await auth.RefreshTokenAsync();

		Console.WriteLine($"***** OUTPUT - lt2Base.AccessToken (?): {lt2Tokens.AccessToken}\n\n");
		return lt2Tokens;
	}

	[HttpPost]
	public async Task<ActionResult<string>> RevokeToken(L2TBase l2tTokens)
	{
		OAuth2Authorizer auth = new()
		{
			CredentialStore = new OAuth2CredentialStore
			//CredentialStore = new OAuth2SessionCredentialStore(HttpContext.Session)
			{
				ClientID = _configuration["TwitterClientID"],
				AccessToken = l2tTokens.AccessToken
			}
		};

		string result = await auth.RevokeTokenAsync();
		Console.WriteLine($"\n\n***** result: {result}\n\n");
		return result;
	}

Error (same for Refresh & Revoke Token):

    fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
          An unhandled exception has occurred while executing the request.
          LinqToTwitter.Common.TwitterQueryException: Missing valid authorization header - Please visit the LINQ to Twitter FAQ (at the HelpLink) for help on resolving this error.
             at LinqToTwitter.Net.TwitterErrorHandler.HandleUnauthorizedAsync(HttpResponseMessage msg)
             at LinqToTwitter.Net.TwitterErrorHandler.ThrowIfErrorAsync(HttpResponseMessage msg)
             at LinqToTwitter.OAuth.OAuth2Authorizer.SendHttpAsync(HttpRequestMessage req)
             at LinqToTwitter.OAuth.OAuth2Authorizer.RefreshTokenAsync()
             at LINQ_To_Twitter_OAuth2_Sample.Server.Controllers.OAuth2Controller.RefreshToken(L2TBase lt2Tokens) in D:\Repos\LINQ_To_Twitter_OAuth2_Sample\LINQ_To_Twitter_OAuth2_Sample\Server\Controllers\OAuth2Controller.cs:line 102
             at lambda_method16(Closure , Object )
             at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
             at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
             at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
             at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
             at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
             at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
             at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
             at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
             at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
             at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
             at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
             at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
             at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
             at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
             at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
             at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
             at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by JoeMayo** [comment]
The first place I would look is if you're losing session state. IIRC, Web API doesn't turn session state on by default and you have to do it explicitly. This SO post might help: https://stackoverflow.com/questions/9594229/accessing-session-using-asp-net-web-api

**Comment by JeepNL** [comment]
I've made some changes and I just saw it working one time (RefreshToken) after I cleared all the Application Storage with Developer Tools ... And that it didn't work after that is probably because the tokens have been updated (at Twitter), but I didn't update them yet in my code so the follow-up requests used the wrong tokens. 

I noticed also that once I do a restart of the app the HttpContext.Session became invalid, and I needed to authorize with Twitter again so it creates a new and valid `.AspNetCore.Session` cookie.

Looking better at what's happening with the HttpContext.Session made all the difference (your SO tip, thank you.).

So there are a couple of things I did wrong, and I need to check them but I think I'm almost there :)

**Comment by JoeMayo** [comment]
IIRC, the `RefreshTokenAsync`, might actually give you a new token.

**Comment by JeepNL** [comment]
Yes, it gives a new RefreshToken and AccessToken.

But good news: it works! - RefreshToken & RevokeToken. And I've implemented the new L2T 'Me' endpoint as well so I can Welcome the user by (Twitter) name (or handle).

I'll update my repo in 15 minutes and I'll close this issue now because it wasn't a LT2 issue but a 'Jaap Issue'. And I've seen a lot of them ... these 'Jaap Issues' 😉
