### ISSUE TITLE
L2T v6 / Twitter API v2 - error uploading image(s)

### ISSUE THREAD

**Issue by JeepNL** [JoeMayo/LinqToTwitter#281]
Config:
 * L2T v6 
 * Twitter API v2  
 * OAuth2 2.0 settings - Type of App: Web App

When I use the following code in the (server) Web API part of my hosted Blazor WASM application

		string mediaCategory = "tweet_image";
		string uploadsFolder = Path.Combine(_webHostEnvironment.ContentRootPath, "Upload", "Images");
		string filePath = Path.Combine(uploadsFolder, "FNL3hb8XsAIwyOC.jpg");

		Media? media = await twitterCtx.UploadMediaAsync(System.IO.File.ReadAllBytes(filePath), "image/jpg", mediaCategory);

(sample code from console media demos here:) https://github.com/JoeMayo/LinqToTwitter/blob/914f6c2cad4298dd075ac1e98bf0daa67a1fb87e/Samples/LinqToTwitter6/Console/ConsoleDemo.CSharp/ConsoleDemo.CSharp/MediaDemos.cs#L179

I am getting the error below at `twitterCtx.UploadMediaAsync`. Posting a tweet without an image works.
````
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      LinqToTwitter.Common.TwitterQueryException: Unhandled Error - LINQ to Twitter wasn't able to parse Twitter error message. Please copy this message, with the Detail property contents and the query you were using (how to reproduce) to Joe Mayo at https://github.com/JoeMayo/LinqToTwitter/issues.
         at LinqToTwitter.Net.TwitterErrorHandler.BuildAndThrowTwitterQueryException(String responseStr, HttpResponseMessage msg)
         at LinqToTwitter.Net.TwitterErrorHandler.HandleGenericErrorAsync(HttpResponseMessage msg)
         at LinqToTwitter.Net.TwitterErrorHandler.ThrowIfErrorAsync(HttpResponseMessage msg)
         at LinqToTwitter.Provider.TwitterExecute.HandleResponseAsync(HttpResponseMessage msg)
         at LinqToTwitter.Provider.TwitterExecute.InitAsync(String url, Byte[] data, IDictionary`2 postData, String contentType, String mediaCategory, Boolean shared, CancellationToken cancelToken)
         at LinqToTwitter.Provider.TwitterExecute.PostMediaAsync(String url, IDictionary`2 postData, Byte[] data, String name, String fileName, String contentType, String mediaCategory, Boolean shared, CancellationToken cancelToken)
         at LinqToTwitter.TwitterContext.UploadMediaAsync(Byte[] media, String mediaType, IEnumerable`1 additionalOwners, String mediaCategory, Boolean shared, CancellationToken cancelToken)
         at LinqToTwitter.TwitterContext.UploadMediaAsync(Byte[] media, String mediaType, String mediaCategory, Boolean shared, CancellationToken cancelToken)
         at LINQ_To_Twitter_OAuth2_Sample.Server.Controllers.TweetController.Post(L2TTweet l2tTweet) in D:\Repos\LINQ_To_Twitter_OAuth2_Sample\LINQ_To_Twitter_OAuth2_Sample\Server\Controllers\TweetController.cs:line 56
         at lambda_method20(Closure, Object)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 POST https://127.0.0.1/Tweet/Post application/json;+charset=utf-8 276134 - 500 - text/plain;+charset=utf-8 262.9928ms
```

**Comment by JeepNL** [comment]
FYI 3 days ago (May 23rd) Twitter [announced](https://twittercommunity.com/t/v1-1-media-endpoints-available-for-essential-access-in-the-twitter-api-v2/171664) V1.1 Media endpoints are now available for Essential access too in the Twitter API v2

**Comment by JoeMayo** [comment]
Thanks - do you have a copy of the JSON error document that Twitter is sending? 

Their error document formats vary between endpoints and occasionally change and I put this code in so people will send me the JSON, which will help me figure out how to parse as many different formats as possible.

**Comment by JeepNL** [comment]
The client post response I'm getting is not from Twitter I think, see this Edge Dev Tools Screenshot


![Screenshot 2022-05-29 140244](https://user-images.githubusercontent.com/39458532/170867291-28037924-e35b-4b6a-b4ac-25fc83da5bb3.jpg)

The Server Controller console error.

```
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 POST https://127.0.0.1/Tweet/Post application/json;+charset=utf-8 545
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'LINQ_To_Twitter_OAuth2_Sample.Server.Controllers.TweetController.Post (LINQ_To_Twitter_OAuth2_Sample.Server)'
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[102]
      Route matched with {action = "Post", controller = "Tweet", page = ""}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.ActionResult`1[LINQ_To_Twitter_OAuth2_Sample.Shared.Models.L2TTweet]] Post(LINQ_To_Twitter_OAuth2_Sample.Shared.Models.L2TTweet) on controller LINQ_To_Twitter_OAuth2_Sample.Server.Controllers.TweetController (LINQ_To_Twitter_OAuth2_Sample.Server).
***** filePath: D:\Repos\LINQ_To_Twitter_OAuth2_Sample\LINQ_To_Twitter_OAuth2_Sample\Server\Upload\Images\FNL3hb8XsAIwyOC.jpg
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[105]
      Executed action LINQ_To_Twitter_OAuth2_Sample.Server.Controllers.TweetController.Post (LINQ_To_Twitter_OAuth2_Sample.Server) in 203.1754ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'LINQ_To_Twitter_OAuth2_Sample.Server.Controllers.TweetController.Post (LINQ_To_Twitter_OAuth2_Sample.Server)'
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      LinqToTwitter.Common.TwitterQueryException: Unhandled Error - LINQ to Twitter wasn't able to parse Twitter error message. Please copy this message, with the Detail property contents and the query you were using (how to reproduce) to Joe Mayo at https://github.com/JoeMayo/LinqToTwitter/issues.
         at LinqToTwitter.Net.TwitterErrorHandler.BuildAndThrowTwitterQueryException(String responseStr, HttpResponseMessage msg)
         at LinqToTwitter.Net.TwitterErrorHandler.HandleGenericErrorAsync(HttpResponseMessage msg)
         at LinqToTwitter.Net.TwitterErrorHandler.ThrowIfErrorAsync(HttpResponseMessage msg)
         at LinqToTwitter.Provider.TwitterExecute.HandleResponseAsync(HttpResponseMessage msg)
         at LinqToTwitter.Provider.TwitterExecute.InitAsync(String url, Byte[] data, IDictionary`2 postData, String contentType, String mediaCategory, Boolean shared, CancellationToken cancelToken)
         at LinqToTwitter.Provider.TwitterExecute.PostMediaAsync(String url, IDictionary`2 postData, Byte[] data, String name, String fileName, String contentType, String mediaCategory, Boolean shared, CancellationToken cancelToken)
         at LinqToTwitter.TwitterContext.UploadMediaAsync(Byte[] media, String mediaType, IEnumerable`1 additionalOwners, String mediaCategory, Boolean shared, CancellationToken cancelToken)
         at LinqToTwitter.TwitterContext.UploadMediaAsync(Byte[] media, String mediaType, String mediaCategory, Boolean shared, CancellationToken cancelToken)
         at LINQ_To_Twitter_OAuth2_Sample.Server.Controllers.TweetController.Post(L2TTweet l2tTweet) in D:\Repos\LINQ_To_Twitter_OAuth2_Sample\LINQ_To_Twitter_OAuth2_Sample\Server\Controllers\TweetController.cs:line 41
         at lambda_method56(Closure, Object)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 POST https://127.0.0.1/Tweet/Post application/json;+charset=utf-8 545 - 500 - text/plain;+charset=utf-8 217.0776ms
```

And this is my (simplified,  using a static image) controller
Error at `await twitterCtx.UploadMediaAsync`

```
[HttpPost]
public async Task<ActionResult<L2TTweet>> Post(L2TTweet l2tTweet)
{
	if (string.IsNullOrEmpty(l2tTweet.AccessToken) || string.IsNullOrEmpty(l2tTweet.RefreshToken) || string.IsNullOrEmpty(l2tTweet.Text))
		return BadRequest("AccessToken, RefreshToken and Text are required.");

	OAuth2Authorizer auth = OAuth2Helper.Authorizer(l2tTweet.AccessToken, l2tTweet.RefreshToken);
	TwitterContext twitterCtx = new TwitterContext(auth);

	Tweet? tweet = new();
	string mediaCategory = "tweet_image";

	string uploadsFolder = Path.Combine(_webHostEnvironment.ContentRootPath, "Upload", "Images");
	string filePath = Path.Combine(uploadsFolder, "FNL3hb8XsAIwyOC.jpg");
	
	byte[] imageFileBytes = System.IO.File.ReadAllBytes(filePath);

	Media? media = await twitterCtx.UploadMediaAsync(imageFileBytes, "image/jpg", mediaCategory);
	
	if (media == null)
		return BadRequest("Problem uploading media.");

	tweet = await twitterCtx.TweetMediaAsync(l2tTweet.Text, new List<string> { media.MediaID.ToString() });

	l2tTweet.TweetId = tweet?.ID;
	return Ok(l2tTweet);
}
```

**Comment by JeepNL** [comment]
Today I'm again trying to make this work, and looked further into the Twitter API v2.

Looking at [Twitter API Tools](https://developer.twitter.com/apitools/api?endpoint=%2F2%2Ftweets&method=post) (_Twitter API v2 calls_) you can add `media_ids` to `POST /2/yweets`

But when I search for Upload Media I see this endpoint [in the v1.1 API](https://developer.twitter.com/en/docs/twitter-api/v1/media/upload-media/api-reference/post-media-upload-init) only and not in the v2 API documentation

Maybe this is why it fails?

**Comment by JoeMayo** [comment]
JeepNL,

I think I know what is happening here. There isn't a v2 endpoint for upload media yet, so you have to use the v1.1, which is the one that you're using. According to this forum discussion, you can use the v1.1 `UploadMedia` method to get `mediaIds`. Then pass those `mediaIds` to the v2 `TweetMediaAsync` method, like you're doing above. 

> [Forum Discussion](https://twittercommunity.com/t/how-to-show-an-image-in-a-v2-api-tweet/163169/6)

I believe you're running into problems because OAuth2 doesn't work with v1.1 endpoints. However, OAuth1.0A works for the `TweetMediaAsync` method. In my demo code, the `MediaDemos` class has an example of doing this with OAuth1.0A. So, if you instantiate a separate `TwitterContext`, but use an OAuth1.0A authorizer, it should work.

Alternatively, you can have two `TwitterContext` instances: one with an OAuth2 authorizer (for `TweetMediaAsync`) and the other with an OAuth1.0A authorizer (for `UploadMediaAsync`).

Regards,

Joe

**Comment by JeepNL** [comment]
Thank you Joe for your reply. Yes, I figured as much when I took a deeper dive into the Twitter API docs a week ago. 

If I'm correct, this means the user needs to authenticate my app twice at Twitter, redirection will occur twice, once for OAuth1.0A and once for OAuth2. I don't think I can get the OAuth1.0A Consumer Token and Secret with the OAut2 access token?  

Authenticating the user twice (for the same service) is not something I want to do. The average end user wouldn't understand that. If something like that would happen to me I would directly stop the auth process, thinking something fishy is going on.

In the Forum Discussion the Twitter Devs are saying they're working on a v2 upload endpoint, but they are pretty vague about when this is going to happen.

And I encountered some other problems/bugs with the V2 endpoints concerning images too. I've [created a topic on one of them](https://twittercommunity.com/t/bug-twitter-api-v2-get-2-tweets-doesnt-return-expected-response-all-the-information/172063) in the forum with a link to a predefined Twitter API Playground query to reproduce the result I'm getting. Click & run to reproduce, but after more than 3 weeks they haven't responded.
