### ISSUE TITLE
Can't parse XML error when trying to start OAuth with incorrect Callback URL setting

### ISSUE THREAD

**Issue by msvprogs** [JoeMayo/LinqToTwitter#342]
### Please let us know what you use:

- .NET SDK version: 6.0.400
- LINQ To Twitter Version: 6.15.0
- Twitter API version (v1/v2) both

### Describe the issue
I have a Twitter App with misconfigured Callback URL for OAuth user authentication (Actually, I've forgotten to append port number to it when was configuring authentication settings in Developer portal).  An attempt to start OAuth process through the LinqToTwitter library results in the following exception. I thought that error code and message should have been parsed and placed in the corresponding fields of the exception object.

### Error / Console Output
```
Title: Unable to Parse Response - please examine Detail property
Type: XML Formatted Error
Reason: Forbidden
Errors:
Details: <?xml version='1.0' encoding='UTF-8'?><errors><error code="415">Callback URL not approved for this client application. Approved callback URLs can be adjusted in your application settings</error></errors>
 ---> LinqToTwitter.Common.TwitterQueryException: Unable to Parse Response - please examine Detail property
   at LinqToTwitter.Net.TwitterErrorHandler.BuildAndThrowTwitterQueryException(String responseStr, HttpResponseMessage msg)
   at LinqToTwitter.Net.TwitterErrorHandler.HandleGenericErrorAsync(HttpResponseMessage msg)
   at LinqToTwitter.Net.TwitterErrorHandler.ThrowIfErrorAsync(HttpResponseMessage msg)
   at LinqToTwitter.OAuth.AuthorizerBase.HttpGetAsync(String oauthUrl, IDictionary`2 parameters)
   at LinqToTwitter.OAuth.AuthorizerBase.GetRequestTokenAsync(String callback)
   at LinqToTwitter.AspNetAuthorizer.BeginAuthorizeAsync(Uri callback, Dictionary`2 parameters)
   at LinqToTwitter.MvcAuthorizer.BeginAuthorizationAsync(Uri callback, Dictionary`2 parameters)
```

**Comment by JoeMayo** [comment]
Thanks for reporting. I'm still chasing the various error formats that the Twitter API returns. :)
