### ISSUE TITLE
Unparseable error: 429 - Too Many Requests on CreateFavoriteAsync() method

### ISSUE THREAD

**Issue by msvprogs** [JoeMayo/LinqToTwitter#363]
### Please let us know what you use:

- .NET SDK version: 6.0.400
- LINQ To Twitter Version: 6.15.0
- Twitter API version (v1/v2) v1 here

### Describe the issue
Hello, sorry to bother you so much 🙏 

I found another error that isn't parsed correctly. 
It is 429 error status on the `CreateFavorite` endpoint (v1), which arises when app-wide limit of 1000 likes/day has been exceeded. 

_Yes, I know that there is a v2 endpoint for this action, so I've successfully switched to it 😄_

### Error / Console Output
```
Title: Unhandled Error - LINQ to Twitter wasn't able to parse Twitter error message. Please copy this message, with the Detail property contents and the query you were using (how to reproduce) to Joe Mayo at https://github.com/JoeMayo/LinqToTwitter/issues.
Type:
Reason: Too Many Requests (HTTP 429 - Too Many Requests)
Errors:
Details:
 ---> LinqToTwitter.Common.TwitterQueryException:  - Please visit the LINQ to Twitter FAQ (at the HelpLink) for help on resolving this error.
   at LinqToTwitter.Net.TwitterErrorHandler.HandleTooManyRequestsAsync(HttpResponseMessage msg)
   at LinqToTwitter.Net.TwitterErrorHandler.ThrowIfErrorAsync(HttpResponseMessage msg)
   at LinqToTwitter.Provider.TwitterExecute.HandleResponseAsync(HttpResponseMessage msg)
   at LinqToTwitter.Provider.TwitterExecute.PostFormUrlEncodedToTwitterAsync[T](String method, String url, IDictionary`2 postData, CancellationToken cancelToken)
   at LinqToTwitter.TwitterContext.CreateFavoriteAsync(UInt64 id, Boolean includeEntities, CancellationToken cancelToken)
```

**Comment by JoeMayo** [comment]
Thanks for reporting - I'm still tracking down all these different error response formats.

**Comment by JoeMayo** [comment]
Resolved by #367 - chose to deprecate v1 since it was replaced by Likes in v2.
