### ISSUE TITLE
Unable to use UploadMediaAsync

### ISSUE THREAD

**Issue by LarsAndreas** [JoeMayo/LinqToTwitter#372]
### Please let us know what you use:

- .NET SDK version:
net7.0
- LINQ To Twitter Version:
6.15.0

### Describe the issue

```
var tweetText = prompt;

var builder = new ConfigurationBuilder()
            .SetBasePath(Directory.GetCurrentDirectory())
            .AddJsonFile("appsettings.json", optional: false);

IConfiguration config = builder.Build();

TwitterApiSettings twitterApiSettings = config
    .GetSection("TwitterApiSettings").Get<TwitterApiSettings>() ?? throw new Exception("Could not find TwitterApiSettings");

var auth = new SingleUserAuthorizer
{
    CredentialStore = new SingleUserInMemoryCredentialStore
    {
        ConsumerKey = twitterApiSettings.ConsumerKey,
        ConsumerSecret = twitterApiSettings.ConsumerSecret,
        AccessToken = twitterApiSettings.AccessToken,
        AccessTokenSecret = twitterApiSettings.AccessTokenSecret
    }
};

await auth.AuthorizeAsync();

var twitter = new TwitterContext(auth);

byte[] fileData;
using (FileStream fileStream = File.OpenRead(filePath))
{
    // Create a byte array to hold the contents of the stream
    fileData = new byte[fileStream.Length];

    // Read the contents of the stream into the byte array
    fileStream.Read(fileData, 0, fileData.Length);
}

Console.WriteLine($"FileDataLength: {fileData.Length}");

var media = await twitter.UploadMediaAsync(
    fileData,
    "image/png",
    "tweet_image");

await twitter.CreateMediaMetadataAsync(
    media.MediaID,
    "This is my alt text");


var result = twitter.TweetMediaAsync(
    text: tweetText, //This is the alt of the image
    mediaIds: new[] { media.MediaID.ToString() }
);
```

I am getting an unexpected error, and I don't know what to do here.

### Error / Console Output
```
Unhandled exception. LinqToTwitter.Common.TwitterQueryException: Unhandled Error - LINQ to Twitter wasn't able to parse Twitter error message. Please copy this message, with the Detail property contents and the query you were using (how to reproduce) to Joe Mayo at https://github.com/JoeMayo/LinqToTwitter/issues.
   at LinqToTwitter.Net.TwitterErrorHandler.BuildAndThrowTwitterQueryException(String responseStr, HttpResponseMessage msg)
   at LinqToTwitter.Net.TwitterErrorHandler.HandleGenericErrorAsync(HttpResponseMessage msg)
   at LinqToTwitter.Net.TwitterErrorHandler.ThrowIfErrorAsync(HttpResponseMessage msg)
   at LinqToTwitter.Provider.TwitterExecute.HandleResponseAsync(HttpResponseMessage msg)
   at LinqToTwitter.Provider.TwitterExecute.InitAsync(String url, Byte[] data, IDictionary`2 postData, String contentType, String mediaCategory, Boolean shared, CancellationToken cancelToken)
   at LinqToTwitter.Provider.TwitterExecute.PostMediaAsync(String url, IDictionary`2 postData, Byte[] data, String name, String fileName, String contentType, String mediaCategory, Boolean shared, CancellationToken cancelToken)
   at LinqToTwitter.TwitterContext.UploadMediaAsync(Byte[] media, String mediaType, IEnumerable`1 additionalOwners, String mediaCategory, Boolean shared, CancellationToken cancelToken)
   at LinqToTwitter.TwitterContext.UploadMediaAsync(Byte[] media, String mediaType, String mediaCategory, Boolean shared, CancellationToken cancelToken)
   at Program.<Main>$(String[] args) in C:\Users\LarsA\Repos\T\T\Program.cs:line 61
   at Program.<Main>(String[] args)
```

**Comment by JoeMayo** [comment]
If you can, it would be helpful if you could grab the response from Twitter API when your application throws. That way, I can find out why it isn't parsing. I have one fix on a message that I haven't deployed yet, so I might have gotten it.

The first thing that pops out with your code is that it doesn't verify that the upload has succeeded before attaching metadata or tweeting. The issue is that it might take a second on the back end for the image to completely upload (eventual consistency). The trick is to poll until the upload was successful. Please look at the `CreateMetadataAsync` demo in the sample code for an example of what I mean:

https://github.com/JoeMayo/LinqToTwitter/blob/main/Samples/LinqToTwitter6/Console/ConsoleDemo.CSharp/ConsoleDemo.CSharp/MediaDemos.cs

**Comment by LarsAndreas** [comment]
I tried copying the code used in the example now, but I still get the same message on UploadMediaAsync. Where can I look at the error message? It is thrown at the line where I call:

```
byte[] fileData = File.ReadAllBytes(filePath);

Console.WriteLine($"FileDataLength: {fileData.Length}");

var media = await twitter.UploadMediaAsync(
    fileData,
    "image/png",
    "tweet_image");
```

```
FileDataLength: 3147977
Unhandled exception. LinqToTwitter.Common.TwitterQueryException: Unhandled Error - LINQ to Twitter wasn't able to parse Twitter error message. Please copy this message, with the Detail property contents and the query you were using (how to reproduce) to Joe Mayo at https://github.com/JoeMayo/LinqToTwitter/issues.
   at LinqToTwitter.Net.TwitterErrorHandler.BuildAndThrowTwitterQueryException(String responseStr, HttpResponseMessage msg)
   at LinqToTwitter.Net.TwitterErrorHandler.HandleGenericErrorAsync(HttpResponseMessage msg)
   at LinqToTwitter.Net.TwitterErrorHandler.ThrowIfErrorAsync(HttpResponseMessage msg)
   at LinqToTwitter.Provider.TwitterExecute.HandleResponseAsync(HttpResponseMessage msg)
   at LinqToTwitter.Provider.TwitterExecute.InitAsync(String url, Byte[] data, IDictionary`2 postData, String contentType, String mediaCategory, Boolean shared, CancellationToken cancelToken)
   at LinqToTwitter.Provider.TwitterExecute.PostMediaAsync(String url, IDictionary`2 postData, Byte[] data, String name, String fileName, String contentType, String mediaCategory, Boolean shared, CancellationToken cancelToken)
   at LinqToTwitter.TwitterContext.UploadMediaAsync(Byte[] media, String mediaType, IEnumerable`1 additionalOwners, String mediaCategory, Boolean shared, CancellationToken cancelToken)
   at LinqToTwitter.TwitterContext.UploadMediaAsync(Byte[] media, String mediaType, String mediaCategory, Boolean shared, CancellationToken cancelToken)
   at Program.<Main>$(String[] args) in C:\Users\LarsA\Repos\T\T\Program.cs:line 53
   at Program.<Main>(String[] args)
```
