### ISSUE TITLE
Exception thrown when using a Stream in 4.2.0 beta on MVC Core

### ISSUE THREAD

**Issue by StevenVanRossen** [JoeMayo/LinqToTwitter#90]
Hi Joe,

When using a stream on MVC Core with version 4.2.0 beta, an exception is thrown "The archive entry was compressed using an unsupported compression method."

Any clues where this error would come from?

Code used is close per the sample on the Wiki:

                await (from strm in TwitterCtx.Streaming
                        where strm.Type == StreamingType.Filter &&
                        strm.Track == "linqtotwitter"
                        select strm).StartAsync(async strm =>
                        {
                            string message = string.IsNullOrEmpty(strm.Content) ? "Keep-Alive" : strm.Content;

                            if (message == "Keep-Alive")
                            {
                                IsRunning = true;
                            }
                            else
                            {
                                Status tweet = new Status();
                                tweet = JsonConvert.DeserializeObject<Status>(message);
                                _log.LogInformation("Received Tweet: " + tweet.Text);

                                IsRunning = true;
                            }
                        });

**Comment by JoeMayo** [comment]
Just checked and didn't get an error. Are you still seeing this or was it temporary?

**Comment by StevenVanRossen** [comment]
I just checked. The exception is still there (on Core 1.1): InnerException message is "The archive entry was compressed using an unsupported compression method."
Let me know if you want me to check extra details of the exception.

**Comment by StevenVanRossen** [comment]
Here is some detail:
   at System.IO.Compression.Inflater.Inflate(FlushCode flushCode)
   at System.IO.Compression.Inflater.ReadInflateOutput(Byte* bufPtr, Int32 length, FlushCode flushCode, Int32& bytesRead)
   at System.IO.Compression.Inflater.InflateVerified(Byte* bufPtr, Int32 length)
   at System.IO.Compression.Inflater.Inflate(Byte[] bytes, Int32 offset, Int32 length)
   at System.IO.Compression.DeflateStream.<ReadAsyncCore>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LinqToTwitter.TwitterExecute.<QueryTwitterStreamAsync>d__50.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LinqToTwitter.TwitterContext.<ExecuteAsync>d__121`1.MoveNext()

**Comment by urffin** [comment]
@JoeMayo, I have same error. Can you fix it?

**Comment by urffin** [comment]
Problem solved after update to core 2.0

**Comment by StevenVanRossen** [comment]
Same here. Fixed on core 2.0. Closing
